version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram_bot_db
    restart: always
    environment:
      POSTGRES_DB: TelegramFormBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TelegramFormBot"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: TelegramFormBot
      DB_USER: postgres
      DB_PASSWORD: root
    command: ["java", "-jar", "app.jar"]

volumes:
  db_data: